import os

#TYPEFACE = "Avenir Next"
TYPEFACE = "FreeSans"

SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480

SPLASH_TIME = 3000

HOME_ITEM_WIDTH = None
HOME_ITEM_HEIGHT = None
HOME_IMG_WIDTH = 120
HOME_IMG_HEIGHT = 120
HOME_IMG_PADY = (50, 10)
HOME_IMG_PADX = 50
HOME_ITEM_FONT_SIZE = 20
HOME_TOP_MARGIN = 80
HOME_LEFT_RIGHT_MARGIN = 60

HOME_SETTINGS_TEXT_PADY = 16
HOME_SETTINGS_ITEM_WIDTH = 360
HOME_SETTINGS_ITEM_HEIGHT = 60
HOME_SETTINGS_TOP_MARGIN = 380

HOME_ITEM_COLOR = "#EEEEEE"

INFO_NUMBER_FONT_SIZE = 20
INFO_POKEMON_FONT_SIZE = 28

NAV_ITEM_SELECTED_COLOR = "#DDDDDD"
NAV_ITEM_BORDER_COLOR = "#BBBBBB"
NAV_ITEM_FONT_SIZE = 20

HEADER_HEIGHT = 60
STATS_HEIGHT = 200

STATS_LABEL_CHARS = 8
STATS_VALUE_CHARS = 11
STATS_VALUE_WRAP_LENGTH = 140

BASE_STATS_LABEL_CHARS = 12
BASE_STATS_VALUE_CHARS = 3

DESCRIPTION_FONT_SIZE = 16
DESCRIPTION_HEIGHT = 84
EVOLUTION_HEIGHT = 64
EVO_FONT_SIZE = 22
EVO_ITEM_PAD_Y = (20, 0)

BLACK = "#000000"
BACKGROUND_COLOR = "#FFFFFF"
EVOLUTION_BACKGROUND = "#EEEEEE"

RPI_UNAMES = {"armv6l", "armv7l"}

IS_RUNNING_ON_RPI = os.uname()[4] in RPI_UNAMES
